import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Search, BookOpen } from "lucide-react";
import api from "../../services/api";
import { formatCurrency } from "../../utils/formatters";

export default function ManageCourses() {
  const [rows, setRows] = useState([]); const [q, setQ] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get("/admin/courses").then((r) => setRows(r.courses || [])).finally(() => setLoading(false)); }, []);
  const filtered = rows.filter((r) => `${r.title} ${r.category} ${r.coach?.name || ""}`.toLowerCase().includes(q.toLowerCase()));
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold text-slate-900">Courses</h2><p className="text-sm text-slate-500 mt-1">All coach-created courses</p></div><div className="bg-white rounded-2xl shadow-sm p-4"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search courses..." className="w-full rounded-lg border px-9 py-2 text-sm" /></div></div><div className="bg-white rounded-2xl shadow-sm overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{["Course", "Coach", "Category", "Students", "Price", "Status", "Action"].map((c) => <th key={c} className="px-5 py-3 text-left text-xs font-bold uppercase text-slate-500">{c}</th>)}</tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={7} className="py-10 text-center text-slate-400">Loading...</td></tr> : filtered.length === 0 ? <tr><td colSpan={7} className="py-10 text-center text-slate-400"><BookOpen className="mx-auto mb-2" />No courses found</td></tr> : filtered.map((c) => <tr key={c.id} className="hover:bg-slate-50"><td className="px-5 py-3 font-semibold">{c.title}</td><td className="px-5 py-3">{c.coach?.name || "-"}</td><td className="px-5 py-3">{c.category}</td><td className="px-5 py-3">{c.students || 0}</td><td className="px-5 py-3">{formatCurrency(c.price || 0, c.currency || "INR")}</td><td className="px-5 py-3">{c.status}</td><td className="px-5 py-3"><Link className="text-indigo-600 font-semibold" to={`/admin/courses/${c.id}`}>View/Edit</Link></td></tr>)}</tbody></table></div></div>;
}